{% set name = "darabonba-core" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/darabonba-core-{{ version }}.tar.gz
  sha256: 82a0a9b2ffe8cd7d707192975d1c6352da82fcb1c80ea78b0b440202cd7a77d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alibabacloud-tea
    - requests >=2.21.0,<3.0.0
    - aiohttp >=3.7.0,<4.0.0

test:
  imports:
    - darabonba
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aliyun/tea-python
  summary: The darabonba module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_file: LICENSE-2.0.txt
  dev_url: https://github.com/aliyun/tea-python
  doc_url: https://github.com/aliyun/tea-python/blob/master/README.md

extra:
  recipe-maintainers:
    - xylar
