schema_version: 1

context:
  name: darabonba-core
  version: "1.0.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 1026c965b4c2b48f89995eadad7ab780a03959812c8f8de4670eb44c48e5b179

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - alibabacloud-tea
    - requests >=2.21.0,<3.0.0
    - aiohttp >=3.7.0,<4.0.0
    - websocket-client >=1.6.0,<2.0.0
tests:
  - python:
      imports:
        - darabonba
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: The darabonba module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_file: LICENSE-2.0.txt
  homepage: https://github.com/aliyun/tea-python
  repository: https://github.com/aliyun/tea-python
  documentation: https://github.com/aliyun/tea-python/blob/master/README.md

extra:
  recipe-maintainers:
    - xylar
